udfps: Implement missing cancel method in XiaomiUdfpsHandler
fixes:
device/xiaomi/sm8350-common/udfps/UdfpsHandler.cpp:143:16: error: allocating an object of abstract class type 'XiaomiUdfpsHandler'
  143 |     return new XiaomiUdfpsHandler();
      |                ^
hardware/xiaomi/fingerprint/include/UdfpsHandler.h:21:18: note: unimplemented pure virtual method 'cancel' in 'XiaomiUdfpsHandler'
   21 |     virtual void cancel() = 0;
      |                  ^
1 error generated.
21:31:42 ninja failed with: exit status 1
There were 4 actions that completed after the action that failed. See verbose.log.gz for their output.